### ISSUE TITLE
requestAnimationFrame ?

### ISSUE THREAD

**Issue by asafyish** [cyclejs/cycle-core#100]
Hi,

I saw that Rx supports requestAnimationFrame as a scheduler (Well, not Rx directly, but [Rx-Dom](https://github.com/Reactive-Extensions/RxJS-DOM/blob/master/src/requestanimationframescheduler.js)).
Is that something that can benefit Cycle ? didn't find any reference to it in the source code.

And BTW, Great work on the stream branch, it looks much easier to grasp.

**Comment by staltz** [comment]
Hi @asafyish , yes, requestAnimationFrame scheduler should work fine with Cycle since it's entirely Rx-based. I know that mercury framework also uses rAF when changing the DOM. I'll probably do that at some point too.

**Comment by staltz** [comment]
Will move this to Cycle DOM.
