### ISSUE TITLE
Controls are broken in the many example

### ISSUE THREAD

**Issue by unbracketed** [cyclejs/cycle-core#114]
The slider and Remove button don't work consistently for newly added items.

Steps to reproduce:

1. browse to the many example
2. verify slider and Remove work for the default item
3. Refresh the page
4. Add a new item and see whether its inputs work. Occasionally, the input controls work for the new item but often they don't. Try adding additional items
5. When the additional items aren't working, altering the state of the default item seems to activate the event handlers for the additional items

Chrome Version 42.0.2311.135 unknown (64-bit)

Parent: #108

**Comment by staltz** [comment]
Thanks for the detailed bug report @unbracketed. This seems odd, and could have been fixed already in the `nostream` branch, where I just tested and I can't seem to reproduce the bug.

**Comment by unbracketed** [comment]
I'll try a few more tests in other browsers/OS. FWIW this was in the `nostream` branch

**Comment by staltz** [comment]
This issue was moved to cyclejs/cycle-web#12
