### ISSUE TITLE
Components as Web Components 

### ISSUE THREAD

**Issue by erykpiast** [cyclejs/cycle-core#119]
We started discussion [here](https://github.com/staltz/cycle/issues/84), I just want to structurize it a bit.

**Comment by cem2ran** [comment]
As requested, an example of a (cycle) soon to be web component: http://codepen.io/cem2ran/pen/xGKpBE?editors=101 :tada:

**Comment by erykpiast** [comment]
I've created similar example, but a bit earlier, for Cycle 0.20.
https://github.com/erykpiast/autocompleted-select/blob/master/src/js/create-component.js

**Comment by staltz** [comment]
@cem2ran I like your codepen example, and it shows how it might be important to find a proper way to pass properties to the top-level `computer` function which is given to `applyToDOM`. In your example the web component is not using the attributes it was given. The exciting is that I think issue #116 will be able to solve this problem, so we don't need to add another API shortcut for this use case.

**Comment by staltz** [comment]
This issue was moved to cyclejs/cycle-web#10
