### ISSUE TITLE
IE8 Support (Cycle is so close, why not?)

### ISSUE THREAD

**Issue by apiv** [cyclejs/cycle-core#123]
One of the main reasons we chose virtual-dom was its support for IE8. Cycle also will run in IE8, and I've managed to get the todomvc-cycle demo working in IE8 by doing the following:

1. Making [this change](https://github.com/Reactive-Extensions/RxJS/pull/719) to RxJS. This is a fix for RxJS in IE8 that allows `querySelectorAll` to work properly with `Rx.Observable.fromEvent`
2. Removing the es6-map dependency, which has a dependency which uses a few reserved words in its code. (obj.delete, obj.function, etc).
3. Using the following polyfills (in this specific order):
   - webreflection/ie8 (in conditional IE HTML tags)
   - es5-shim
   - es5-sham
   - babel-polyfill

The only issue IE8 has with Cycle, and the only change that would need to occur in Cycle would be with the es6-map dependency. Adding the polyfills listed in step 3 would be done in the project of the developer who is implementing Cycle.

I'm unsure of what stance Cycle takes on IE8 compatibilty, but at this point I feel that it is so close that it might as well support IE8. I am proposing two possible options:

1. Remove the es6-map polyfill from cycle as a dep. Leave polyfilling of ES6 features up to the developer who is implementing Cycle, in their own project.
2. Create a compat-mode build, which will run browserify with the following options: `-tg [babelify --optional es3.propertyLiterals]`. This will do a global transform of all dependencies of cycle as babelify goes through them. This will escape the reserved words in the dependencies of es6-map.

**Comment by staltz** [comment]
:+1:

**Comment by Mouvedia** [comment]
:+1:

**Comment by bdjibril** [comment]
:+1:

**Comment by yordis** [comment]
Why we should do it? :-1:

**Comment by staltz** [comment]
This should be in Cycle DOM repo, and it's outdated since we're not using anymore e.g. es6-map dependency.
