### ISSUE TITLE
`-` compulsory for custom element names

### ISSUE THREAD

**Issue by staltz** [cyclejs/cycle-core#126]

**Comment by cgeorg** [comment]
This will bring the custom element implementation in line with the web component spec - it future proofs the framework against people registering custom element names that clash with element names that exist in the HTML spec, or that may be added in the future.

The [naming spec](http://w3c.github.io/webcomponents/spec/custom/#concepts) outlines the following requirements:

* Must be an [NCName](http://www.w3.org/TR/1999/REC-xml-names-19990114/#NT-NCName)
* Must include a dash (U+002D)
* Must not contain upper case letters
* Must not be one of:
 * annotation-xml
 * color-profile
 * font-face
 * font-face-src
 * font-face-uri
 * font-face-format
 * font-face-name
 * missing-glyph

**Comment by staltz** [comment]
This issue was moved to cyclejs/cycle-web#5
