### ISSUE TITLE
Custom element with varying root element loses its event handlers

### ISSUE THREAD

**Issue by staltz** [cyclejs/cycle-core#127]
To reproduce, take the synthetic/nested example, change the custom element to use `h(content < 500 ? 'h2.innerRoot' : 'h3.innerRoot', ...)` as the vtree. Then when clicking the custom element, event handlers might be temporarily pointing to the wrong element. Also notice the lack of switching functionality in diff and patch, which makes the top-most diff and patch emit on rawRootElem$ multiple consecutive times because of previous unremoved waitForChildrenStreams still emitting.

**Comment by erykpiast** [comment]
I'm just curious, is it bug in Cycle itself or in VDOM?

**Comment by staltz** [comment]
Bug in Cycle. I found it while building #116, but it's a corner case bug. I have a good idea how to fix this, but I'm just documenting it here now so I can postpone fixing it, because I want to focus on #116 for now. In general, nothing to worry about.

**Comment by staltz** [comment]
This issue was moved to cyclejs/cycle-web#4
