### ISSUE TITLE
Missing Id?

### ISSUE THREAD

**Issue by arlair** [cyclejs/cycle-core#130]
Hi, I found this project today and it looks really interesting. Nice work :+1: 

In this example:
http://jsbin.com/fayenexoyu/1/edit?html,js,output

It seems to output an empty id. Is this a bug?

    <div id="" class="target cycleCustomElement-MY-ELEMENT">

**Comment by staltz** [comment]
Could be. I'll investigate if it's Cycle or virtual-dom.

**Comment by staltz** [comment]
This issue was moved to cyclejs/cycle-web#3
