### ISSUE TITLE
Leading Space on class

### ISSUE THREAD

**Issue by arlair** [cyclejs/cycle-core#131]
A minor issue I noticed. A leading space on class before target in this example:

http://jsbin.com/mosojosera/1/edit?html,js,output

    <button class=" target cycleCustomElement-MY-ELEMENT"><p>Some content</p></button>

**Comment by staltz** [comment]
Will fix :+1:

**Comment by staltz** [comment]
This issue was moved to cyclejs/cycle-web#2
