### ISSUE TITLE
setting scrollTop on div doesn't work properly

### ISSUE THREAD

**Issue by fab1an** [cyclejs/cycle-core#134]
I have a function that grows the inside of a div and scrolls the outer div to the end by setting `scrollTop`. For some reason the last value of scrollTop isn't applied.

```javascript
let {h} = Cycle;

let _test = Rx.Observable.interval(50)
  .take(11);

function computer(interactions) {
  return _test.map((sum) => {
    let count = sum+1;
    let size = count*22
    let scrollTop = Math.max(0, 22*count-220);

    console.log(count, size, scrollTop);

    return h('div', {className: 'scrollDiv',
                     scrollTop: scrollTop},
            [h('div', {className: 'spacer',
                       style: {height: `${size}px`}})
            ]
      );
  });
}

Cycle.applyToDOM('#main', computer);
```

The css:

```css
div.scrollDiv {
  overflow-y: scroll;
  height: 220px;
  width: 400px;
  border: 1px solid black;
}
```

Screenshot, where the div should be scrolled down, but isn't:
![screen shot 2015-06-17 at 15 55 41](https://cloud.githubusercontent.com/assets/55547/8208705/55862662-1509-11e5-96c4-6e86a7691ec0.png)

After the last iteration the scrollTop property is reported to be `110px`, but stays at the previous value of `88px`.

**Comment by fab1an** [comment]
This might be a bug in virtual-dom. I guess there's a race-condition where the larger `scrollTop` is set before the new height of the inner div is set.

**Comment by staltz** [comment]
This issue was moved to cyclejs/cycle-web#6
