### ISSUE TITLE
Create localStorage driver

### ISSUE THREAD

**Issue by staltz** [cyclejs/cycle-core#141]
Draft API:

```js
function storageDriver(request$) {
  // ...
  return responseCollection;
}
```
where `request$` is an Observable of `request` objects, following the template:
```js
let request = {
  target: 'local', // 'local' | 'session'
  action: 'setItem', // 'setItem' | 'removeItem' | 'clear'
  key: 'mykey',
  value: 'myvalue'
};
```
Defaults are set as `'local'` for `target`, and `'setItem'` for `action`.

`responseCollection` is a queryable collection of Observables, following the template:
```js
let responseCollection = {
  local: { // for localStorage
    key(n) // function returning Observable of the nth key
    getItem(key) // function returning Observable of values
  },
  session: { // for sessionStorage
    key(n) // function returning Observable of the nth key
    getItem(key) // function returning Observable of values
  }
};
```

**Comment by staltz** [comment]
When ready, use in TodoMVC-Cycle

**Comment by kahlil** [comment]
Hi @staltz I am interested in this feature. Would be happy to help. Do you want to write this from scratch or maybe driverize this: https://github.com/nramadas/Storable? (to which @highondrive pointed me to in Gitter)

**Comment by staltz** [comment]
Might be a good first task to help. Check out how TodoMVC-Cycle has a small local-storage driver.

**Comment by kahlil** [comment]
Ok will have a look at that. Thanks.

**Comment by kahlil** [comment]
@staltz this is how I understood your Draft API: https://github.com/kahlil/cycle-storage-driver
can you have a quick look and let me know if I am on the right track before I go ahead and add tests and stuff?

It's just a few lines of code.

**Comment by staltz** [comment]
Overall looks good, although I'd change this signature
```js
doAction(target = 'local', action = 'setItem', key = undefined, value = undefined) 
```
to
```js
doAction(key, value, target = 'local', action = 'setItem') 
```

Because if you call `doAction('fooAge', 30)`, then we should assume the defaults `target = 'local'` and `action = 'setItem'`, but the first signature wouldn't do that, it would take `target= 'fooAge'` and `action =  30`.

**Comment by kahlil** [comment]
OK will do, thanks.

Should I refactor the function to take an object instead of params since the cycle linter does not like 4 params?

**Comment by staltz** [comment]
Perhaps yes

**Comment by kahlil** [comment]
ok done https://github.com/kahlil/cycle-storage-driver/blob/master/lib/doAction.js

**Comment by kahlil** [comment]
Can this issue be closed?

**Comment by staltz** [comment]
Yes

**Comment by kahlil** [comment]
:smile:

**Comment by Frikki** [comment]
I don’t think it’s working as it ought to. See this issue https://github.com/cyclejs/cycle-storage-driver/issues/7
