### ISSUE TITLE
Create HTTP ("XHR") Driver

### ISSUE THREAD

**Issue by staltz** [cyclejs/cycle-core#142]
Based on RxJS-DOM's Ajax helpers. See https://github.com/Reactive-Extensions/RxJS-DOM/issues/66

**Comment by staltz** [comment]
Based on RxJS-DOM's Ajax helpers. See https://github.com/Reactive-Extensions/RxJS-DOM/issues/66

**Comment by staltz** [comment]
A draft. https://gist.github.com/staltz/c7142dec80ac077ef8ed

Anyone got suggestions or comments? It's surprisingly simple because it's a thin wrapper over RxJS-DOM.

**Comment by staltz** [comment]
Important use case for POST mentioned by @ccapndave:
> my app uploads multiple images at the same time to the same endpoint, and each of them has a progress listener and then a green checkmark when they have completed their upload

**Comment by ivan-kleshnin** [comment]
Maybe it was better to choose any non-Rx AJAX library like [Axios](https://github.com/mzabriskie/axios)?
I don't see any connection between DOM and AJAX and I don't underestand why RxJS-Dom puts ajax helpers in the `DOM.ajax`. Looks like a mess to me.

**Comment by staltz** [comment]
> Maybe it was better to choose any non-Rx AJAX library like Axios?

I'm not familiar with Axios, so I don't know if it can handle cancelation, but normally Promise-based ajax such as the standard `Fetch` simply don't support request cancellation as old XHR does.

> I can't underestand why RxJS-Dom chose to put AJAX helpers in the DOM.ajax namespace. Looks like a coupled mess to me. 

We will split. See https://github.com/Reactive-Extensions/RxJS-DOM/issues/66

> responses.DOM also can't be read as a normal language.

Can you elaborate? `responses.DOM`, or `responses.driverName` is a Cycle.js idiom.

**Comment by ivan-kleshnin** [comment]
> I'm not familiar with Axios, so I don't know if it can handle cancelation, but normally Promise-based ajax such as the standard Fetch simply don't support request cancellation as old XHR does.

You're right, it can't.

> We will split. See Reactive-Extensions/RxJS-DOM#66

> These could be respectively split into:
rx.dom.events.js
rx.dom.ajax.js
rx.dom.sse.js
rx.dom.websockets.js
rx.dom.webworkers.js
rx.dom.mutations.js
rx.dom.geolocation.js
rx.dom.schedulers.js
rx.dom.filereader.js

In your proposition AJAX is still namespaced under DOM. I think library name is confusing.
If it's DOM specific why AJAX? If it's not DOM specific why such name :confused: ?

> Can you elaborate? responses.DOM, or responses.driverName is a Cycle.js idiom.

Ah, this is driver name... I first thought it was HTTP responses.

**Comment by staltz** [comment]
> In your proposition AJAX is still namespaced under DOM. I find the library name confusing.
If it's DOM specific why AJAX? If it's not DOM specific why such name :confused: ?

Good point, I'll check what Matt thinks about making `rx.ajax.js` instead of `rx.dom.ajax.js`.

**Comment by leoasis** [comment]
Would it make sense to support some way to pass context data?

Use case: I want to create something optimistically, and I create it in memory with a client ID and a status of "creating", then issue a POST. If the POST succeeds, I want to unset the "creating" flag of the thing with client ID. If the POST fails, I want to remove the thing with that client ID.

**Comment by staltz** [comment]
Very good example use case. I'll try to see how it would look under the proposed API.

**Comment by cem2ran** [comment]
I would appreciate a unified mental model among drivers. I don't know if this was the plan or not or even a good idea, but I'd rather do the following than filtering: 
```javascript
drivers.HTTP.get(api_endpoint)
```
**http.js**
```javascript
var Rx = require('rx-dom');

// makeHTTPDriver is a factory, but it has no parameters.
// It would be simpler to just export httpDriver() function,
// but maybe it would make sense to give some parameters
// to the factory. I just don't know which parameters would
// those be. A cache? Suggestions please.
function makeHTTPDriver() {
  return function httpDriver(request$) {
    return {
        get: function(key){
            return request$.map(function (request) {
              var response$ = Rx.DOM.ajax(request);
              response$.request = request.url || request;
              return response$;
            })
            .filter(function(res$){
                return res$.request.indexOf(key) === 0
            });
        }
    }
  }
}

module.exports = makeHTTPDriver;
```

Not sure if this could be extended to: HTTP.post() also, etc?

I also played a little around with the ajax webcomponent in polymer (iron-ajax) for the fun of it. Not working 100% as it only fires a response event the first time. not sure if interop or iron-ajax issue:
https://github.com/cem2ran/cycle-http-driver/blob/master/examples/iron-ajax/src/index.js#L36-L42

**Comment by staltz** [comment]
@cem2ran We already discussed a consistent API in https://github.com/cyclejs/cycle-core/issues/116 and the conclusion was it's best to let drivers specify their own API. The gist is: different drivers need different API for `params` in `get(...params)` anyway.

**Comment by Willmo36** [comment]
If Axios isn't an option how about Superagent? I'm under the impression Rx-dom isn't isomorphic/universal. An Rx wrapper round Superagent could cover that nicely?

**Comment by ivan-kleshnin** [comment]
> If Axios isn't an option how about Superagent? I'm under the impression Rx-dom isn't isomorphic/universal. An Rx wrapper round Superagent could cover that nicely?

Superagent isn't even Promise based...

**Comment by Willmo36** [comment]
Does it have to be? It supports request cancelations with `abort`.

**Comment by staltz** [comment]
Currently considering these 
https://www.npmjs.com/package/xmlhttprequest
https://www.npmjs.com/package/http-browserify

**Comment by ArnoBuschmann** [comment]
http-browserify -> not sure if it is good to take sides for a module bundler, no matter if Browserify, Gulp or Webpack.

**Comment by charles0431** [comment]
Sent from Yahoo Mail on Android

**Comment by staltz** [comment]
So I just successfully implemented the HTTP Driver with superagent. I'm thinking I'll stay with this one since it's universal ("isomorphic", some day I'll stop mentioning what universal corresponds to) and popular.

It was quite easy to code the HTTP Driver so if someone wants a different flavor, they can always implement their own driver.

**Comment by erykpiast** [comment]
:+1:

**Comment by ArnoBuschmann** [comment]
:+1:

**Comment by staltz** [comment]
Check https://github.com/cyclejs/cycle-http-driver
I'll finish up wrapping the basic stuff, then publish to npm. We can continue this discussion in that repo's issues.

**Comment by leoasis** [comment]
awesome @staltz ! :+1:

**Comment by staltz** [comment]
This shows how to use it https://github.com/cyclejs/cycle-http-driver/blob/master/examples/search/search.js
