### ISSUE TITLE
Interested in creating an interactive cycle tutorial

### ISSUE THREAD

**Issue by jessep** [cyclejs/cycle-core#146]
Hiya! I'm going to start building things with cycle as a way to get to know it. I had the idea that it would be fun and charmingly recursive to learn cycle by using it to build a slick interactive cycle tutorial. 

I'll probably do this anyway, but it would be fun to have hope that maybe, one day, if it turns out well, it could be included in the cycle repo in the docs section. Would that be something you'd be open to @staltz?

**Comment by staltz** [comment]
Cool! Sounds like a plan, and I suppose there is still some space on the side menu in cyclejs docs site. Or maybe it could be under a "Try it" section like some sites have (if I recall correctly, kotlin lang has such thing online). Curious what you come up with. :)

**Comment by jessep** [comment]
Wonderful :100:

**Comment by jessep** [comment]
Oh wow, I hadn't seen the docs site yet!
