### ISSUE TITLE
Mediator pattern to promote loosely coupling drivers api

### ISSUE THREAD

**Issue by valerysntx** [cyclejs/cycle-core#148]
Guys, cyclejs is nice! 
I would like to hear some mention, regarding ``` makeRequestProxies ``` and ```callDrivers``` apis.
Just wondering if it be more naturally to follow with mediator pattern and provide something like channels to drivers api?

**Comment by staltz** [comment]
Hi! `makeRequestProxies` and `callDrivers` are not APIs, these are internal functions to the framework. Can you give an example of what you would like to see?

**Comment by valerysntx** [comment]
Sure, you right about internal functions. Assume listening to server initiated push notifications, and naive driver implementation for that scenario, as example. Does it fit core concepts? What about tight coupling between observables? I can be wrong, but it seems mediator pattern approach can fit here.

-----Original Message-----

**Comment by staltz** [comment]
> Assume listening to server initiated push notifications, and naive driver implementation for that scenario, as example. Does it fit core concepts?

Yes that does, in fact there is an example on the docs showing that. http://cycle.js.org/drivers.html#example-driver-implementation

**Comment by neverfox** [comment]
Mediator pattern? Lord, I certainly hope Cycle doesn't introduce OOP patterns. I do functional programming to get away from all of that.
