### ISSUE TITLE
Documentation for async obervables?

### ISSUE THREAD

**Issue by tmcw** [cyclejs/cycle-core#150]
It doesn't [appear like RxJS's map method](http://rxmarbles.com/#map) can be async - is there another operator that is?

```js
function main(responses) {
  return {
    DOM: responses.DOM.get('textarea.input-value', 'keyup')
      .map(SOME_ASYNC_OPERATION)
      .map(value => h('div#wrap.flex', [
          h('div.px2.py2.bg-blue.white', 'documentation.js demo')
      ])
    };
}
```

My usecase is running a textarea worth of input through a documentation generator and showing the result on the right side of the page. The doc generator is async (a stream), and thus results aren't immediately available. Could there be an example of a cycle.js app interacting with an async API, whether AJAX or a local library?

**Comment by staltz** [comment]
flatMap

**Comment by tmcw** [comment]
[flatMap isn't in rxmarbles](http://rxmarbles.com/) - going to the [rxjs page](https://reactive-extensions.github.io/RxJS/) ⇢ [dive in!](https://reactive-extensions.github.io/RxJS/#Dive In!) ⇢ [documentation](https://github.com/Reactive-Extensions/RxJS/tree/master/doc) ⇢ [api](https://github.com/Reactive-Extensions/RxJS/tree/master/doc/api) ⇢ err, [core](https://github.com/Reactive-Extensions/RxJS/tree/master/doc/api/core) -> [observable](https://github.com/Reactive-Extensions/RxJS/blob/master/doc/api/core/observable.md) -> [flatMap](https://github.com/Reactive-Extensions/RxJS/blob/master/doc/api/core/operators/selectmany.md)

It appears that flatMap is an alias for selectMany?

**Comment by staltz** [comment]
Yes I know flatMap isn't in RxMarbles because it's harder to render as a dynamic diagram. ReactiveX.io is the home for rx documentation. Tip: flatMap is often the only operator you need. You can mimic delay with flatMap. You can mimic filter with flatMap. Even map itself.

**Comment by staltz** [comment]
Don't use the selectMany alias. It's idiomatically a secondary alias while flatMap is the primary.

**Comment by tomchentw** [comment]
flayMap +1
