### ISSUE TITLE
Driver order affects outgoing observables

### ISSUE THREAD

**Issue by thatsmydoing** [cyclejs/cycle-core#151]
In http://jsfiddle.net/37m5qfzy/ pressing the button should perform 3 console.logs, 2 for the drivers and 1 for the subscription, but only 2 of them actually register.

Placing the after driver before DOM, makes all 3 logs fire. Another solution is calling shareReplay(1) for out$

Also, if out$ is not used in the DOM driver, it also works http://jsfiddle.net/37m5qfzy/2/

**Comment by thatsmydoing** [comment]
Well, the latest cycle-web fixes this. I guess it was just the event stream not being a hot observable. I always just assumed it was.

**Comment by staltz** [comment]
Interesting! Thanks for re-testing and closing the issue.
