### ISSUE TITLE
Cycle.js and D3

### ISSUE THREAD

**Issue by neverfox** [cyclejs/cycle-core#154]
I'm hoping to try my hand at using Cycle to render D3 visualizations but could use some advice. D3 is part DOM-manipulator and part algorithm library, so I could see the need for a D3 driver perhaps, though I could also see using the React driver in combination with some of the React+D3 techniques that some people have worked out. One thing that's important for me is to get the full use of the transition effects that D3 is able to generate on data changes so direct use of SVG elements is probably out. What do you think would be the best way to weave it in to Cycle, assuming you're familiar with the D3 way of doing things?

**Comment by staltz** [comment]
> assuming you're familiar with the D3 way of doing things?

Not actually familiar, no. I also have a hard time understanding D3's value.

I encourage you to try making a D3 driver (I'm just one person and can't make all the drivers). But also if you're interested in SVG in Cycle, here are two examples: https://github.com/phadej/graafi and https://github.com/staltz/rxmarbles. In RxMarbles I'm also including some animations: https://github.com/staltz/rxmarbles/blob/master/src/components/diagram/diagram-view.js#L115-L155

**Comment by neverfox** [comment]
Thanks for those links. My initial idea for a D3 driver would probably involve a write stream of render functions (closures over changing data) and a read stream of query-able events.

As for D3's value, I think most of it is in its library of layouts and algorithms, i.e. things you wouldn't want to have to write yourself over and over. Formidable Labs, for example, has stripped out the DOM manipulation in favor of React but kept the math.

**Comment by erykpiast** [comment]
@neverfox, are you doing something regarding this currently? I'm highly interested in and I could help,  I guess.

**Comment by neverfox** [comment]
I may be working on a project shortly that will need something like this and hopefully the outcome will be the start of a coherent driver that I could make available.

**Comment by danielbushman** [comment]
I also might be interested in working on this.

**Comment by mrtns** [comment]
@justinwoo has shared a sample project using Cycle and D3 here: http://qiita.com/kimagure/items/3020b0a7d08da3b5ce34

**Comment by erykpiast** [comment]
Do I understand correctly that all the code that connects D3 with Cycle is this?

```
makeDatamapDriver(region) {
  return function datamapDriver(input$) {
    input$.subscribe(() => {...});
  }
}
```
