### ISSUE TITLE
Cannot set property 'inherits' of undefined

### ISSUE THREAD

**Issue by a3gis** [cyclejs/cycle-core#156]
Hello,

I am running into the following error using webpack to build a very basic CycleJS project:

    var inherits = this.inherits = Rx.internals.inherits = function (child, par

    TypeError: Cannot set property 'inherits' of undefined`

The error occurs when importing @cycle/core.

Here's my webpack configuration:

    module.exports = {
        entry: './src/main.js',
        output: {
            path: __dirname,
            filename: 'bundle.js'
        },
        module: {
            loaders: [
                { loader: 'babel-loader', query: {compact: false} }
            ]
        }
    };

Thanks!

**Comment by a3gis** [comment]
Nevermind, problem solved. For future reference, babel was processing node_modules as well, which somehow caused the error. Solution:

    { loader: 'babel-loader', exclude: /node_modules/, query: {compact: false} }

**Comment by gchudnov** [comment]
Just bumped into the same issue, described it here: Reactive-Extensions/RxJS#850

**Comment by gchudnov** [comment]
The problem was resolved in Rx (v3.0.1).

**Comment by staltz** [comment]
Should be solved in Cycle Core v3

**Comment by TSMMark** [comment]
Has `exclude` been renamed to `ignore` in a later babel version? http://babeljs.io/docs/usage/options/
