### ISSUE TITLE
a slew of questions

### ISSUE THREAD

**Issue by ccorcos** [cyclejs/cycle-core#160]
This library/pattern is amazing. This is everything I've been looking for! Very nice job. I'm very eager to build something with this, but I have a slew of questions for you:

- With all these observable streams, can we serialize the state of the entire application and restore it? 

In Meteor particularly, when new code is deployed and pushed to cordova apps and browsers, the app is serialized into local storage, refreshed, and then application is restored as if nothing happened at all. If you can trivially serialize a cycle.js app and restore it, that would be awesome!

- Is there a Route driver? How does routing work? Not just with browser history, but internally? For example, how might a build the equivalent of a UITabBarController or a UINavigationController component?

Modern mobile applications with Tab view controllers and Nav view controllers (like an Instagram app) don't have a linear history because each tab has a different set of histories that can be infinitely nested. When you switch between tabs or push and pop on a navigation stack, the scroll position and state of the view is remembered and everything. This means we can use a simple browser history to control the state of the view. 

- How do you handle cachine HTTP requests and responses?

When a user leaves a certain page, I set a timeout to clear the cached data after some time, unless the user comes back to the page. Would this be implemented within a driver? It seems like we could create a driver to abstract the default HTTP driver much like the labeledSlider component abstracts the slider component.

On a similar note, the same type of driver could be used over a web socket for reactive data, listening for changes and caching the subscription.

Also, what if you want to create your own abstraction for a specific REST api. Would you create a bunch of helper functions and use the raw HTTP driver or would you build your own driver abstraction?

- How do DOM animations work? 

Animations are inherently procedural which makes things tricky, but React does a pretty good job implementing animations declaratively with the CSSTransitionGroup component.

Along the same lines, any thoughts on inline styles?

- Are there any projects using Cycle.js on the server with Node? 

It would be really cool to build an isomorphic build system for both client and server.

**Comment by staltz** [comment]
> With all these observable streams, can we serialize the state of the entire application and restore it?
> In Meteor particularly, when new code is deployed and pushed to cordova apps and browsers, the app is serialized into local storage, refreshed, and then application is restored as if nothing happened at all. If you can trivially serialize a cycle.js app and restore it, that would be awesome!

Yes. Supposing state is an object or an instance from Immutable.js, you can have `state$` Observable which emits these state objects. We should serialize the state object, not the state$ Observable. That said, I don't have time myself to focus on hot reloading, and there is a standing issue for this https://github.com/cyclejs/cycle-core/issues/46. Would be great to have some contributors.

> Is there a Route driver? How does routing work? Not just with browser history, but internally? For example, how might a build the equivalent of a UITabBarController or a UINavigationController component?
> Modern mobile applications with Tab view controllers and Nav view controllers (like an Instagram app) don't have a linear history because each tab has a different set of histories that can be infinitely nested. When you switch between tabs or push and pop on a navigation stack, the scroll position and state of the view is remembered and everything. This means we can use a simple browser history to control the state of the view. 

Read this issue https://github.com/cyclejs/cycle-core/issues/37 and this one https://github.com/cyclejs/cycle-core/issues/159#issuecomment-125799908

> How do you handle cachine HTTP requests and responses?
> When a user leaves a certain page, I set a timeout to clear the cached data after some time, unless the user comes back to the page. Would this be implemented within a driver? It seems like we could create a driver to abstract the default HTTP driver much like the labeledSlider component abstracts the slider component.
> On a similar note, the same type of driver could be used over a web socket for reactive data, listening for changes and caching the subscription.

It's not complicated to extend HTTP Driver to have cache. A request object can have an option for time-to-live, then when the driver receives the request object, it keeps the response and the respective request in a Map. When a new request comes in it is checked against that Map. Alternatively, the request object can have an option `fresh` which always ignores cache. 

> Also, what if you want to create your own abstraction for a specific REST api. Would you create a bunch of helper functions and use the raw HTTP driver or would you build your own driver abstraction?

I don't know which of these I would use, they all seem plausible, however I think I would just use the HTTP driver as is.

> How do DOM animations work?
> Animations are inherently procedural which makes things tricky, but React does a pretty good job implementing animations declaratively with the CSSTransitionGroup component.

This is still an open issue how to do animations in the best possible way. I have been using [RxTween](https://github.com/staltz/rxtween) in RxMarbles to accomplish it: https://github.com/staltz/rxmarbles/commit/f0245e71fee5975554d19098fc9722e87f66163b#diff-ae39f1737136b513253fc639deba4244R115 but I know Netflix folks have better ideas and solutions to this: https://gist.github.com/eplawless/d5a79021999413c187ea

> Along the same lines, any thoughts on inline styles?

It's good.

> Are there any projects using Cycle.js on the server with Node?
> It would be really cool to build an isomorphic build system for both client and server.

Not that I know of, but I'd use plain RxJS on Node.js, because Cycle.js is for user interfaces.

**Comment by ccorcos** [comment]
> Supposing state is an object or an instance from Immutable.js, you can have state$ Observable which emits these state objects. We should serialize the state object, not the state$ Observable.

What worries me here is that components can mask their state behind a closure. Here's a simple example: 

Suppose you have a tab-based app. Each view may have some internal state that isnt returned as a request stream because nothing else uses that information. The scroll position of a component is a perfect example of this. But what if I want to save a components scroll position and restore the component to the previous scroll position when I come back to it (much like any tab-based iOS app). This will require the view to output a stream of scroll events. The parent component (the tab view controller) would have merge that stream into its state, changing the "initialScrollTop" prop of the view component. The tab view would then have to return its state to its parent and so forth all the way to the top-level component. Then finally, we can serialize the latest value emited from the top-level component's state, and restore the entire app to this exact state. 

This doesn't seem like the most elegant way of doing things. It would be really cool is there was an `internalState$` stream returned by a component (including scroll position and other opaque state properties), which the parent component can keep track of based on the key to that component, and can be restored more transparently. Its just a thought... I'm not sure the best way of doing this. But it would be really convenient if the entire application state could be encapsulated by a single referentially transparent object.

I'm doing this exact thing right now in React by passing a mutable object, called an "instance", down to child components as props, assigning values to that object (mutably) during `componentWillUnmount` and reading values off that object in `componentWillMount` to restore the previous state. Its a hack, but it works, and I can see an object representing the entire state of the UI at any one point.

For example:

```jsx
var Counter = React.createClass({
  displayName: 'Counter',
  mixins: [React.addons.PureRenderMixin],
  propTypes: {
    instance: React.PropTypes.object.isRequired
  },
  getInitialState: function() {
    return this.props.instance.state || {count:10}
  },
  inc: function() {
    this.setState({count: this.state.count + 1})
  },
  componentWillUnmount: function() {
    this.props.instance.state = this.state
  },
  render: function() {
    return <div>{this.state.count}</div>
  }
})

var Article = React.createClass({
  displayName: 'Article',
  mixins: [React.addons.PureRenderMixin],
  propTypes: {
    instance: React.PropTypes.object.isRequired,
    text: React.PropTypes.string.isRequired
  },
  componentDidMount: function() {
    this.getDOMNode().scrollTop = this.props.instance.scrollTop || 0
  },
  componentWillUnmount: function() {
    this.props.instance.scrollTop = this.getDOMNode().scrollTop
  },
  render: function() {
    return <div>{this.props.article}</div>
  }
})
```

> That said, I don't have time myself to focus on hot reloading, and there is a standing issue for this #46. Would be great to have some contributors.

This is more for development. Very cool, but not exactly what I was getting at. Honestly, I'm a little too entrenched in Meteor. I have yet to do a serious project with my own build tools (gulp, webpack, grunt, etc.). I'm really eager to use my own tools but its a lot of work to get a build pipeline up an running with (1) isomorphic javascript, (2) user authentication, (3) web sockets, and (4) deployment. 

> It's not complicated to extend HTTP Driver to have cache. A request object can have an option for time-to-live, then when the driver receives the request object, it keeps the response and the respective request in a Map. When a new request comes in it is checked against that Map. Alternatively, the request object can have an option fresh which always ignores cache.

I havent used RxJS a whole lot, but here's my go at it. I think this is similarly how you can build a custom REST API driver. Whats really interesting to me here is how a driver can be thought of as just another cycle :)

```js
function fetchDriver({fetch, HTTP}) {
  let cache = {} // fetch cache
  let request$ = Rx.Observable() // HTTP requests

  let response$ = fetch.map( (req) => {
    if (cache[req.url]) {
      return cache[req.url] // found in the cache
    } else {
      request$(req) // request if not found in the cache
    }
  }).filter( x => x != undefined) // filter only the hits

  // catch any HTTP responses, cache them, and emit them as fetch responses.
  HTTP.map(res => {
    let url = res.url
    cache[url] = res
    response$(res)
  })

  return {
    fetch: response$,
    HTTP: request$
  };
}
```

I'm just not sure how you incorporate this cycle into the mix.

> I know Netflix folks have better ideas and solutions to this: https://gist.github.com/eplawless/d5a79021999413c187ea

That looks really clean actually. I could imagine something like this that wraps its children in another cycle.

> Not that I know of, but I'd use plain RxJS on Node.js, because Cycle.js is for user interfaces.

When reading through the documentation and watching your JSConf talk, you mention how the computer and the human can be thought of as just a function. Maybe I'm taking this too far, I think it would be reasonable for the server to act similarly as a cycle. Imagine using a websocket instead of the DOM as the "senses / actuators" of the server. This server cycle could in turn have drivers for making database queries, etc.

**Comment by staltz** [comment]
> Suppose you have a tab-based app. Each view may have some internal state that isnt returned as a request stream because nothing else uses that information. The scroll position of a component is a perfect example of this. But what if I want to save a components scroll position and restore the component to the previous scroll position when I come back to it (much like any tab-based iOS app). This will require the view to output a stream of scroll events. The parent component (the tab view controller) would have merge that stream into its state, changing the "initialScrollTop" prop of the view component. The tab view would then have to return its state to its parent and so forth all the way to the top-level component. Then finally, we can serialize the latest value emited from the top-level component's state, and restore the entire app to this exact state.

> This doesn't seem like the most elegant way of doing things. It would be really cool is there was an internalState$ stream returned by a component (including scroll position and other opaque state properties), which the parent component can keep track of based on the key to that component, and can be restored more transparently. Its just a thought... I'm not sure the best way of doing this. But it would be really convenient if the entire application state could be encapsulated by a single referentially transparent object.

Two things come to mind:

- You can make `internalState$` yourself through custom events in the components
- Each tab as a component is not the only way of building the application. Each tab can be instead simply a pure function, and state can live elsewhere. In Cycle.js, unlike React, it is not "everything is a component". In Cycle.js, small widgets owning transient irrelevant state should be components.

>  havent used RxJS a whole lot, but here's my go at it. I think this is similarly how you can build a custom REST API driver.

Take a look at the source code of HTTP driver.

> Whats really interesting to me here is how a driver can be thought of as just another cycle :)

A driver is not a cycle. Neither is main(). It's main+drivers which make a cycle. 

> Maybe I'm taking this too far, I think it would be reasonable for the server to act similarly as a cycle. Imagine using a websocket instead of the DOM as the "senses / actuators" of the server. This server cycle could in turn have drivers for making database queries, etc.

Read this twitter discussion https://twitter.com/mykola/status/608318513414041600

**Comment by ccorcos** [comment]
hmmm. I have to let this sink in
