### ISSUE TITLE
Firebase Driver

### ISSUE THREAD

**Issue by HighOnDrive** [cyclejs/cycle-core#161]
I've been looking into the possibility of producing a Firebase driver for Cycle.js. Turns out most of the work is already done by re-base. I've initiated an issue at re-base and they are starting to look into it. Here is the link, any advice is welcome:

https://github.com/tylermcginnis/re-base/issues/32#issuecomment-126398738

**Comment by HighOnDrive** [comment]
Some progress being make, see https://github.com/tylermcginnis/re-base/issues/32#issuecomment-126398738

**Comment by dralletje** [comment]
Hey @HighOnDrive , I made a firebase driver!
I tried to make it as declarative as possible, so tell me what you think please! :-)

https://github.com/dralletje/cycle-firebase

**Comment by fiatjaf** [comment]
Why this issue?

**Comment by TylorS** [comment]
Nice work @dralletje I'll look at it soon in the next few days :+1:

**Comment by staltz** [comment]
@dralletje looks good! The API looks decent, with scoping in mind. Just one question, why this name `set$` in `.set$(data: Any): Object` if it is not related to Observables?

**Comment by staltz** [comment]
PS: this issue is to track community effort in making drivers. If a driver ends up being solid and/or used by many, we may consider it "official" and move it to the cyclejs org and npm scope.

**Comment by dralletje** [comment]
@staltz eh my bad, hahaha, it is actually `$set`, because mongo (and more nosql databases?) use `$something` for special case keys. Thanks for pointing it out! :-)
