### ISSUE TITLE
Silent error while working through example code

### ISSUE THREAD

**Issue by bzalasky** [cyclejs/cycle-core#162]
I'm exploring Cycle for a new project, and was checking out the Getting Started section. I errantly entered in Cycle.DOM.h as opposed to CycleDOM.h, and the example wasn't working. However, it failed silently, and I didn't see the "Cannot read property 'h' of undefined" error I would have expected to see. 

Is this a potential pitfall of Babel or Webpack? It doesn't strike me as something that would be inherent in Cycle.

**Comment by bzalasky** [comment]
It seems like it has to do with it being passed to map.

**Comment by staltz** [comment]
Will fix.

**Comment by staltz** [comment]
Fixed and released in v1.0.2
