### ISSUE TITLE
TDD with Cycle.js

### ISSUE THREAD

**Issue by thesameqad** [cyclejs/cycle-core#163]
We are using Cycle.js in our company for over 3 months now and it's time to cover the app with unit tests and start using TDD for new functionality.
Previously, we were using Backbone and I we had pretty decent unit tests coverage there. But, testing reactive application seems to be so much different.
I didn't find any useful documentation or samples on how to do that. I spent the whole day trying to test my intent streams. After digging deeply into observables methods, here is what I came with(this is not the actual code).

//intent
...
	var menu$ = ext.DOM.get('#id', 'keydown').debounce(10).map(function (key){
		return key+1;
	}).filter(function (x) { return x });  
...
//intent.spec
...
           //Calling the stream selector 
            var result = menu$.source.selector({
                keyCode:11
            });
            //Checking that mapping is done correctly 
            expect(result).to.equal(12);
...

This looks really wired and I didn't find any samples, where people are using such approach. I was trying to subscribe to observable and then trigger a keydown event using jQuery, but, the subscription never fired.
What will be the best way to write such unit test?

Thanks in advance.

**Comment by erykpiast** [comment]
I think the way is creating smaller modules containing all transformation logic. Input streams for those modules (in your case `ext.DOM.get('#id', 'keydown')`) can be easily mocked for tests and you can focus on testing your application logic. I wish to do more in this topic, but so far I can show you only one example of TDD Cycle application. It's quite old and uses Cycle 0.x, but I think you can see the pattern there. https://github.com/erykpiast/autocompleted-select/tree/master/src/js/spec

**Comment by staltz** [comment]
Because testing Cycle.js code is basically just about testing Observables, you should follow this: https://github.com/Reactive-Extensions/RxJS/blob/master/doc/gettingstarted/testing.md

Use the virtual time scheduler when it makes sense, or just test non-reactive functions like @erykpiast said.
