### ISSUE TITLE
EPEERINVALID on `npm install @cycle/core`

### ISSUE THREAD

**Issue by Frikki** [cyclejs/cycle-core#164]
@staltz 

## Overview
```
// npm-debug.json
...
1027 error Linux 3.13.0-52-generic
1028 error argv "node" "/home/frikki/.nvm/versions/node/v0.12.7/bin/npm" "i" "@cycle/core" "--save"
1029 error node v0.12.7
1030 error npm  v2.13.4
1031 error code EPEERINVALID
1032 error peerinvalid The package @cycle/core@2.0.0 does not satisfy its siblings' peerDependencies requirements!
1032 error peerinvalid Peer @cycle/dom@3.2.2 wants @cycle/core@1.0.x
1033 verbose exit [ 1, true ]
```

## Motivation
The docs says to install with `npm install @cycle/core`.

## Versions
v2.0.0

## npm and Operating System
npm v2.13.4
Linux Mint 17.1 (Debian)

## Reproduce Error
From the command line, execute `npm install @cycle/core`.

## Related Issues
Issue #154

**Comment by staltz** [comment]
@Frikki for now do `npm install @cycle/core@1.0.2`, because Cycle DOM needs Core v1.x, while you installed Core v2.x

**Comment by staltz** [comment]
Cycle DOM v4 released which solves this issue.

**Comment by Frikki** [comment]
:thumbsup:
