### ISSUE TITLE
Incremental-DOM driver

### ISSUE THREAD

**Issue by TylorS** [cyclejs/cycle-core#165]
I just stumbled across cycle today and it really looks awesome. I've been playing with incremental-dom by using [https://github.com/jsx-ir/jsx-to-idom](https://github.com/jsx-ir/jsx-to-idom) in one of my own personal projects. I thought it would be really awesome to combine the two or maybe even just jsx-ir which would give even more rendering flexibility. 

I'd love to work on this, maybe with a nudge in the right direction =).

What do you think?

**Comment by TylorS** [comment]
I finally got around to doing this.
https://github.com/tylors/cycle-jsx-ir

Love to gather everyone's thoughts.

**Comment by TylorS** [comment]
I don't think that there is much interest here anymore.
@staltz do you think it is safe to close this?

**Comment by staltz** [comment]
Sure
