### ISSUE TITLE
Idea - switch from Rxjs to kefirjs

### ISSUE THREAD

**Issue by dusky3** [cyclejs/cycle-core#166]
Hi there, I find the idea of this project very intriguing and I think you did a great job. 
This is just my 0.02$ but would it be possible to switch from Rx to kefirjs? Or you could just port it to kefirjs in another branch of the project.
I know the cyclejs core depends on Rx heavily, but I think it shouldn't be a problem as kefirjs provides the same functionality as Rx does and this step would massively reduce the size of the cyclejs framework. This would help anyone who creates small applications (like me) where the size matters the most and ~200k minified is quite a lot.

**Comment by staltz** [comment]
It's easier to just make a separate library using Kefir, than to migrate Cycle.js to Kefir. For instance Cycle Core is just about 100 lines of code, it should be simple to make a clone of it with Kefir. Cycle DOM without the custom elements is also rather small.

I'm planning on switching to [ReactiveX/RxJS](https://github.com/ReactiveX/RxJS) once it's ready, it should be a faster RxJS implementation than the current one.

**Comment by dusky3** [comment]
Thank you for the reply @staltz. I think switching to faster RxJS will not solve the problem with the size of the library unless the newer RxJS would be also modular. Another thing is that RxJS has Apache 2.0 license where kefirjs has MIT license which is more open source I think.

I would like to make a clone of cyclejs with kefirjs, but my programming skills aren't on that level yet, I started with programming a year ago and I'm still learning. So for now I can only hope someone will find this idea interesting and make such a clone one day. Meantime I can play with cyclejs with RxJS.

Anyway thank you for your effort in creating this library.

**Comment by gaearon** [comment]
>I think switching to faster RxJS will not solve the problem with the size of the library unless the newer RxJS would be also modular. 

AFAIK modularity was one of the goals of the rewrite.

**Comment by dusky3** [comment]
Thank you for the information @gaearon , that would be great.

**Comment by axefrog** [comment]
Is there any value in perhaps "initializing" Cycle by passing it a reference to the core Rx namespace? That way Cycle could be completely decoupled from its RxJS dependency and work with any library that correctly implements the core set of operators.

**Comment by staltz** [comment]
peerDependencies?

**Comment by axefrog** [comment]
Let's say my dev folder structure is:

A: /dev/node_modules/my_npm_module
B: /dev/projects/amazingness/node_modules

My amazingness project requires 'my_npm_module' and because of the folder structure, I can simultaneously develop that module and amazingness will find it. If, however, my_npm_module requires  Rx, just as my amazingness does, and it's declared as a peerDependency of my_npm_module, will, does that mean that my my_npm_module will still compile and just assume that, at runtime, it will be able to find it once all is said and done?

If so, then :+1: from me :)
