### ISSUE TITLE
Double subscribe to driver output

### ISSUE THREAD

**Issue by secobarbital** [cyclejs/cycle-core#169]
Feeding a driver response into two driver requests will cause the first driver's side-effects to execute twice. In the following code, the console logs ```url``` twice for each click on a link:

```javascript
function makeURLDriver () {
  return function URLDriver (navigate$) {
    return navigate$
      .do(url => console.log('url', url)) // <== executed twice for each url
  }
}

const drivers = {
  DOM: makeDOMDriver('main'),
  URL: makeURLDriver(),
  Fetch: makeFetchDriver()
}

Cycle.run(({DOM, URL, Fetch}) => {
  const navigate$ = DOM.select('a').events('click')
    .map(e => e.currentTarget.href)
  const fetchRequest$ = URL        // <== calling once
    .map(url => `${url}.json`)
  const vtree$ = URL               // <== calling twice
    .map(url => <h1>{url}</h1>)
  return {
    DOM: vtree$,
    URL: navigate$,
    Fetch: fetchRequest$
  }
}, drivers)
```

If we multicast the URL driver response, then it works as expected:

```javascript
Cycle.run(({DOM, URL, Fetch}) => {
  const url$ = URL.share()
  const navigate$ = DOM.select('a').events('click')
    .map(e => e.currentTarget.href)
  const fetchRequest$ = url$
    .map(url => `${url}.json`)
  const vtree$ = url$
    .map(url => <h1>{url}</h1>)
  return {
    DOM: vtree$,
    URL: navigate$,
    Fetch: fetchRequest$
  }
}, drivers)
```

So my question is, given one of the primary use cases for drivers is to isolate side-effects, should we just go ahead and multicast all driver responses that we pass into main?

**Comment by TylorS** [comment]
I think I've experienced this issue as well while developing drivers, but thought it was an issue with my drivers themselves. I just didn't know Rx well enough yet to know this happens. Thanks!

**Comment by staltz** [comment]
This is a typical Rx issue, known as hot (shared) vs cold (not shared). The confusion normally arises because hot is expected to be the default, while cold is the default. To be honest, I wish Rx would make hot the default. I could elaborate on this pain point, but to stay pragmatic on this issue, let's just say as a driver developer, you must decide yourself whether the driver response should be shared or not. I think shared by default makes sense. The cases where you explicitly want cold/nonshared are more rare.

**Comment by secobarbital** [comment]
Got it, thanks! I guess a blurb on the Drivers section of the docs will do, then. Another thing I've noticed in drivers that both of you have written, is you tend to use ```.subscribe()``` while I tend to just stack operations on my inputs and return that as output. The latter feels a bit circular but I think it's OK since there is a subscribe where the emissions get transferred into the proxies. Is that accurate?

**Comment by staltz** [comment]
What do you mean by "stack operations on my inputs and return that as output"?

**Comment by staltz** [comment]
Ok, I might understand what you mean, when I took a look at most drivers. Most of them are backed by subjects, which are hot/shared. This JSONP driver is not, though: https://github.com/cyclejs/cycle-jsonp-driver/blob/master/src/index.js

**Comment by secobarbital** [comment]
Ahh yes that's how I've been writing my drivers. I think I know the problem now. For the URL driver I've been using ```.do(pushState)``` to perform the side-effect. This gets called multiple times when there are multiple subscribers. Rewriting with a ```.subscribe(pushState)``` avoids the issue.

So lesson learned: don't use ```.do()``` for side-effects in drivers.

**Comment by staltz** [comment]
Yeah, I mainly use .do() for debugging logs. Any important side effect should always be in a subscribe (otherwise you might not see the side effect at all since Observables are lazy and .do() does not prompt the laziness to "evaluate").

**Comment by secobarbital** [comment]
Indeed I think my fetch driver suffers from the laziness problem. I should rewrite it along the lines of the JSONP driver.

Can I ask why you emit a meta stream instead of a ```mergedAll``` observable of responses (with each request attached to its corresponding response)? Is there an advantage to that? Finally, since the JSONP response$$ is a cold observable, does that mean Rx is "caching" every response in memory?

**Comment by staltz** [comment]
Returns a metastream so the app developer can choose to `mergeAll` or `switch`. It makes a difference depending what kind of app you are building.

**Comment by secobarbital** [comment]
Got it, thanks!!

**Comment by secobarbital** [comment]
Nothing to fix here. Reopen with doc tag if you want to keep track of the documentation enhancement.
