### ISSUE TITLE
Migrate to RxJS Next

### ISSUE THREAD

**Issue by staltz** [cyclejs/cycle-core#177]
Let's use this issue to document our progress as we migrate.

TODO
- [x] RxJS Next peer dependency in Cycle Core, tests passing
- [x] RxJS Next peer dependency in Cycle DOM, tests passing
- [ ] RxJS Next peer dependency in Cycle HTTP Driver, tests passing
- [ ] Use publishBehavior instead of replay
- [ ] No use of _unsubscribe() in any Cycle code

**Comment by Frikki** [comment]
@TylorS Could you elaborate on the rough edges besides the use of `_unsubscribe()`?

**Comment by TylorS** [comment]
@staltz You had mentioned to me that `lift()` is **not** a one to one equivalent to the previous use of `asObserver()`. I see that as a rough edge. Is there something better?
Also the fact that I seemingly have to use `_unsubscribe()` instead of `unsubscribe()`
Also it's strange that some of the tests are very time sensitive.

**Comment by Frikki** [comment]
@TylorS Which tests were that? Were they consistently time consuming?

**Comment by TylorS** [comment]
@Frikki Check my comments on this commit
https://github.com/TylorS/cycle-core/commit/a4ec0ba787e7a675117bddd458322cebd2f2d6c2

**Comment by TylorS** [comment]
Also, tests take almost 400ms to complete.

**Comment by staltz** [comment]
Each test?

**Comment by TylorS** [comment]
No, overall.

**Comment by Frikki** [comment]
@staltz It’s test no. 8 that takes long time, ~300 ms, because `delay()` only accepts minimum value of `100` if the test shouldn’t fail.

```js
let number$ = Rx.Observable.range(1, 3)
        .concatMap(x => Rx.Observable.of(x).delay(100));
```

**Comment by Frikki** [comment]
@staltz I think we can cross off two bullet points.

**Comment by staltz** [comment]
Cycle DOM and what else?

**Comment by Frikki** [comment]
I thought Cycle HTTP was ready.

**Comment by staltz** [comment]
@Frikki not totally ready https://github.com/cyclejs/cycle-http-driver/pull/21#discussion_r42650320

**Comment by Frikki** [comment]
@staltz But @TylorS wrote, 'Done' two days ago(?!)

**Comment by TylorS** [comment]
Done as in I did what he asked me to. What *should* work doesn't, and what shouldn't work does. If I understand correctly.

**Comment by Frikki** [comment]
Do we have an issue open on what does and doesn’t work?

**Comment by staltz** [comment]
@Frikki just read those comments

**Comment by TylorS** [comment]
That's what this issue is for

**Comment by Frikki** [comment]
I just feel that issues should be broken down into smaller issues and tracked separately. This issue seem to combine all issues into one giant blob of information. While I think it is good to have a combining issue, I think that a milestone would be more appropriate. And, indeed, cycle-http-driver should have its own milestone for RxNext and its own issues on that repo. Likewise, cycle-dom.

**Comment by staltz** [comment]
Yes, let's do that

**Comment by TylorS** [comment]
@staltz I think it's safe to close this as it's being addressed with Cycle Diversity. 
We can reopen if need be.
