### ISSUE TITLE
Audio Driver

### ISSUE THREAD

**Issue by benji6** [cyclejs/cycle-core#180]
Hi, I've been working on a library for declaratively manipulating the Web Audio API called [virtual-audio-graph](https://github.com/benji6/virtual-audio-graph) which is heavily inspired by virtual-dom and react.

It struck me this is probably quite well suited to being a driver for Cycle.js so I've had a go at creating a [cycle-audio-graph](https://github.com/benji6/cycle-audio-graph) driver.

Any feedback on this would be massively appreciated as I'm not that sure about the implementation.

Cheers!

**Comment by staltz** [comment]
Awesome!!!
I'll give it a look. This is a perfectly valid use case for driver. :+1:
