### ISSUE TITLE
Any plans for HTML syntax?

### ISSUE THREAD

**Issue by trusktr** [cyclejs/cycle-core#183]
Something like JSX or t7?

**Comment by TylorS** [comment]
JSX is supported already. The Cycle-DOM driver exports a helper to get started with. https://github.com/cyclejs/cycle-dom/blob/master/docs/api.md#hJSX

There is also the Babel plugin https://github.com/substack/babel-plugin-jsx-factory, and webpack plugin https://github.com/cgeorg/jsx-transform-loader that can be used when setting `jsxPragma=h` if you're using either of those.

**Comment by trusktr** [comment]
@TylorS Cool! I think it might be nice to show a small example of Cycle with that syntax on the front page, which might be really attractive to people coming from React who love JSX.

**Comment by TylorS** [comment]
Many of us purposely choose to suggest the usage of hyperscript. I'll try to find you the link which has some good reasons to learn hyperscript.

**Comment by TylorS** [comment]
https://github.com/jsforum/jsforum/issues/1
