### ISSUE TITLE
Integrate hyperscript-helpers into cycle dom

### ISSUE THREAD

**Issue by staltz** [cyclejs/cycle-core#186]
**On `auto-scope` branch.**

Cycle DOM is to replace `h()` with [hyperscript-helpers](https://github.com/ohanhi/hyperscript-helpers).

Usage should be e.g.
```js
import {div, span, h1, h2, h3, button, makeDOMDriver} from '@cycle/dom';
```

Internally, we can still use `h()` as a lower-level function which hyperscript helpers will use.

**Comment by staltz** [comment]
I'm assigning myself just to reserver this issue, but the real assignee is `Cmdv`.

**Comment by matthewp** [comment]
Is there a good reason why that needs to be bundled? Does it not work well as an external package?

**Comment by staltz** [comment]
Convenience and smarter defaults. I'd recommend using hyperscript-helpers by default.
