### ISSUE TITLE
Add typescript definition files

### ISSUE THREAD

**Issue by milutinovici** [cyclejs/cycle-core#194]
The would especially be useful for new hyperscript helpers, e.g. ul can have only lis as children, enforced by typescript compiler.

**Comment by staltz** [comment]
Thanks for the reminder. You are likely talking about Cycle DOM, not Cycle Core. We have plans to port the entire Cycle DOM to Typescript. In the meanwhile, this issue here is unnecessary to stay open, so I'll close it. But your request is duly noted, not ignored.

**Comment by milutinovici** [comment]
Yeah, I was talking about Cycle DOM, but I thought that the entire library could benefit from typescript, so that's why I put it in core. Nice to know that you agree with me. Can't wait :)

**Comment by TylorS** [comment]
@staltz Have you started this yet?

I was thinking about possibly starting this tonight.

**Comment by staltz** [comment]
@TylorS that'd be great

**Comment by TylorS** [comment]
@staltz I started setting it up a bit, I'm not sure how far I'll get. I'll post a link to the WIP here later.

**Comment by staltz** [comment]
You need a particular branch in this repo for the PRs?

**Comment by TylorS** [comment]
I started on the DOM driver, so yeah maybe a branch there could be good.

**Comment by TylorS** [comment]
I think I'm going to shift focus onto getting the RxJS Next branches working again. The typings for Rx 4 seem quite incomplete. I keep getting a bunch of erros like `replay(1) does not exist on type Observable<any>`.

**Comment by staltz** [comment]
Good idea.
