### ISSUE TITLE
Use a minimum subset of Rx

### ISSUE THREAD

**Issue by staltz** [cyclejs/cycle-core#2]

**Comment by chikamichi** [comment]
Hi, on the same topic, browsing the generated source under dist/, I noticed that RxJS seems to be included twice. As I am new to the project, I don't know yet whether this is intentional (?), but I thought it would be nice reporting this anyway :)

**Comment by staltz** [comment]
Woah. Thanks for reporting. I had no idea that happened.

**Comment by chikamichi** [comment]
Oh :)

Well, this calls for a sanity check of the build I guess :heavy_check_mark: (which is hard to automate).

**Comment by staltz** [comment]
Seems to be a bug in RxJS.
