### ISSUE TITLE
Forwarding Sinks and Deeply Nested Component Hierarchies

### ISSUE THREAD

**Issue by ronag** [cyclejs/cycle-core#202]
Posting this here since I haven't really seen any good practice on how to go about it.

What is the strategy in general with driver dependencies and nested components? Right now parent components are strongly coupled with any nested components since the parent must know what sinks to forward upwards and how to combine them between children.

I'm already at a point with 8 sink drivers that I constantly have to forward upwards. Which results in a lot of boilerplate code...

**Comment by scottcorgan** [comment]
In the [docs](http://cycle.js.org/components.html) and in [this video](https://egghead.io/lessons/rxjs-our-first-component-a-labeled-slider), @staltz recommends using a `props$` Observable. Very similar to props in React. You'd usually make this with a [`combineLatest()`](https://github.com/Reactive-Extensions/RxJS/blob/master/doc/api/core/operators/combinelatest.md) or [`withLatestFrom()`](https://github.com/Reactive-Extensions/RxJS/blob/master/doc/api/core/operators/withlatestfrom.md) from Rx.

**Comment by ronag** [comment]
@scottcorgan: I think you misunderstand. I'm not asking how to propagate attributes down the hierarchy but propagating sinks up the hierarchy, e.g.

```
  const vtree$ = view({
    search$: search.DOM,
    grid$: grid.DOM,
  })
  const msg$ = publish(actions).merge(grid.NATS)
  const request$ = request(actions)
  const prevented$ = actions.dragOver$
  const drops$ = actions.dragOver$

  return {
    DOM: vtree$,
    NATS: msg$,
    HTTP: request$,
    preventDefault: prevented$,
    dropEffect: drops$,
  }
```

**Comment by staltz** [comment]
Sinks up the hierarchy sometimes need a circular dependency of Observables. This is technique I intent to write about on the official docs, just haven't had time for it yet. You can see it in action in TodoMVC Cycle.

>Right now parent components are strongly coupled with any nested components since the parent must know what sinks to forward upwards and how to combine them between children.

Not strongly coupled, because sinks and sources are just interfaces/contracts. Think about how it would be TypeScript for example. The only the parent needs to know about its child is the type/interface of its sources and sinks. Given that, the child could be easily replaced with another child that passes the same interface contract. It's really not coupling, it's just functional types as a contract.

That said, I know what you're talking about regarding boilerplate. It's a conscious choice, it's a framework with little or no magic. Magic and Boilerplate are sometimes two extremes. I was able to reduce most tedious boilerplate by using Observables, which allow you to do a lot with a little amount of code. If you have suggestions how to reduce boilerplate without adding considerable magic, I'm all ears. (`isolate()` was originally not my idea, it came up in one of these issues where people complained about boilerplate of isolating manually).

For the snippet you just wrote, I recommend object spread from ES6:

```js
  const browser = Browser(sources)

  const vtree$ = browser.DOM.map(browser => view({ browser }))

  return {
    ...browser,
    DOM: vtree$,
  }
```

**Comment by ronag** [comment]
Well something like the following would be nice:

```javascript
const a = A(sources)
const b = B(sources)

const vtree$ = view(state$)

return merge({
DOM: vtree$
}, a. b)
```

Where merge would perform a `Observable.merge` on colliding keys.

**Comment by erykpiast** [comment]
I guess this one is doable in a few lines of code. But usually such simple concatenation won't be good enough.

**Comment by ronag** [comment]
@erykpiast: I think it would be enough in 90% of cases. Do you have any examples where you think it wouldn't work?

**Comment by erykpiast** [comment]
No, it's just a feeling. I'm just not sure, if a case when two streams from components have to be `combineLatest` before sending up, it's not common. Let's say, you want to implement component summarizing numbers from custom input components.

```javascript
const i1 = Input(sources);
const i2 = Input(sources);

...

return {
  ...
  sum$: Observable.combineLatest(i1, i2, sum);
};
```

**Comment by ronag** [comment]
Another observation though is that sinks will almost always be combined the same way. So maybe even the driver could specify how sinks should be propagated?

**Comment by staltz** [comment]
@ronag I'm not trying yet to jump to a solution, I'm trying to understand your specific problem. If you could provide actual snippets of your perceived problem, I can make better conclusions what needs to be done, either in user land or framework.

**Comment by ronag** [comment]
@staltz I have already provided examples and explain the problem? Anything specific that is unclear?

**Comment by whitecolor** [comment]
@ronag please could you show your "(error prone) boilerplate" that you do

**Comment by ronag** [comment]
```javascript
  const a = A(sources)
  const b = B(sources)
  const c = C(sources)
  const d = D(sources)

  const vtree$ = Observable.combineLatest(a.DOM, b.DOM, c.DOM, ,d.DOM, (a, b, ,c, d) => view({a, , b, c, d })
  const msg$ = Observable.merge([a.NATS, b.NATS, c.NATS, d.NATS].filter(x => x))
  const request$ = Observable.merge([a.HTTP, b.HTTP, c.HTTP, d.HTTP].filter(x => x))
  const prevented$ = Observable.merge([a.preventDefault, b.preventDefault, c.preventDefault, d.preventDefault].filter(x => x))
  const drops$ = Observable.merge([a. dropEffect, b. dropEffect, c. dropEffect, d. dropEffect].filter(x => x))

  return {
    DOM: vtree$,
    NATS: msg$,
    HTTP: request$,
    preventDefault: prevented$,
    dropEffect: drops$,
  }
```

**Comment by staltz** [comment]
^ @ronag That's not something that is seen in every application, and it seems like a `_.mapValues` is a good approach, I just don't agree yet about `driver.defaultCombine`. It doesn't seem a problem to make your own util and use it in your codebase.

**Comment by ronag** [comment]
@staltz: 

I don't really see how you couldn't see that in many applications? All the cyclejs examples don't have this problem because they don't have the complexity of a real application...

Yes, I will probably make it my own util. It's more about what is the best practice... similar to `isolate`...

**Comment by staltz** [comment]
> I don't really see how you couldn't see that in many applications?

https://github.com/futurice/power-ui is a larger application and it doesn't have that type of wiring.

**Comment by whitecolor** [comment]
@ronag Actually any good boilerplate can be implemented as separate module, you do this - publish and other see (or not see) that it is really useful and apply it in their apps. I to encountered alike problem ("merging sinks"), but not actually the same. Well maybe you will come up with generalized pattern.

**Comment by ronag** [comment]
@staltz: I don't consider that a very large application :) The pages don't even need to have components. But thanks for the link anyways, looks very nice and gave me some good hints.

@whitecolor: Yes, We'll see what I end up and I'll get back with what we end up with.

**Comment by staltz** [comment]
@ronag I understand... and I think the _.mapValues solution is decent. It's also small, meaning probably best to let application developers build it themselves than bake it into the framework. With Cycle, I want to avoid people relying on "magic behavior that the framework does for me which I don't understand", so when they encounter such boilerplate, they can themselves make a decision: (1) I am fine writing this myself, (2) I don't like it, I'll make a small and simple utils for my specific problem. Both of which I believe are healthy against magic.

**Comment by staltz** [comment]
PS: can we close the issue?

**Comment by ronag** [comment]
@staltz: This what we've ended up with:

```javascript
import { Observable } from 'rx'

function flatten() {
  return [].concat(...this)
}

function mapValues(fn) {
  return Object.keys(this)
    .reduce((xs, k) => {
      xs[k] = fn(this[k], k)
      return xs
    }, {})
}

export default function combineSinks(...sinks) {
  const combiners = {
    DOM: x => x.pop(),
  }
  const defaultCombiner = x => Observable.merge(x)
  return sinks
    .map(x => Object.keys(x).map(key => [key, x[key]]))
    ::flatten()
    .reduce((acc, [key, sink]) => {
      (acc[key] = acc[key] || []).push(sink)
      return acc
    }, {})
    ::mapValues((sinks, key) => (combiners[key] || defaultCombiner)(sinks))
}
```

Example:

```javascript
function Foo(sources) {
  const bar = Bar(sources)

  return combineSinks(bar, {
    DOM: view({
      bar$: bar,
    }),
  })
}

export default isolate(Hub)
```

**Comment by staltz** [comment]
:+1:
