### ISSUE TITLE
Not allowed to access package

### ISSUE THREAD

**Issue by jaapster** [cyclejs/cycle-core#203]
When trying to install cycle-core, npm returns a E403

user <user-name> is not allowed to access package @cycle/core : @cycle/core

Same for cycle-dom.

I have never had this issue with any other packages.

Does this need fixing on my side?

**Comment by TylorS** [comment]
I literally just ran this on my end with no issues
```                                                                    
~
❯ npm install @cycle/core rx
/home/tylor
├── @cycle/core@6.0.0 
└── rx@4.0.7 
```

@staltz any ideas?

**Comment by fiatjaf** [comment]
What is your npm version?

**Comment by jaapster** [comment]
npm version is 3.3.12

**Comment by staltz** [comment]
Some people have had problems in the past but due to their own firewall or old npm version, etc, I would not suspect there is a problem on our side. So can you please provide more info? What command did you try to run? What package.json? What node and npm version?

**Comment by ecwyne** [comment]
Did a bit of reading up on this. Could be related to your npm configs

https://github.com/rlidwka/sinopia/issues/243#issuecomment-110316736
https://docs.npmjs.com/misc/config#always-auth

**Comment by jaapster** [comment]
Thanks @ecwyne, that fixed it! The machine I was trying this on had some peculiar config values.
