### ISSUE TITLE
Adoption of "JS standard style"

### ISSUE THREAD

**Issue by whitecolor** [cyclejs/cycle-core#205]
it seems that cyclejs codebase style is pretty close to ["JS standard style"](https://github.com/feross/standard), why not consider its adoption, just for the sake of simplicity? Interesting opinion anyway.

**Comment by whitecolor** [comment]
It gives such warnings on cycle-core/src
```
  ...\cycle.js:3:25: Missing space before function parentheses.
  ...\cycle.js:13:21: Missing space before function parentheses.
  ...\cycle.js:23:30: Missing space before function parentheses.
  ...\cycle.js:26:55: Unexpected trailing comma.
  ...\cycle.js:31:28: Missing space before function parentheses.
  ...\cycle.js:32:26: Missing space before function parentheses.
  ...\cycle.js:34:7: Opening curly brace does not appear on the same line as controlling statement.
  ...\cycle.js:43:32: Missing space before function parentheses.
  ...\cycle.js:46:39: Unexpected trailing comma.
  ...\cycle.js:51:27: Missing space before function parentheses.
  ...\cycle.js:58:23: Missing space before function parentheses.
  ...\cycle.js:63:9: Opening curly brace does not appear on the same line as controlling statement.
  ...\cycle.js:77:28: Missing space before function parentheses.
  ...\cycle.js:88:23: Missing space before function parentheses.
  ...\cycle.js:97:13: Missing space before function parentheses.
  ...\cycle.js:140:6: Unexpected trailing comma.
```

So mostly two "problems")
`Missing space before function parentheses` and `Unexpected trailing comma`

**Comment by staltz** [comment]
No thanks, that "standard" style has nothing of standard in it.

**Comment by whitecolor** [comment]
Can you comment what in particular you don't like about it? Just curious.

**Comment by ichpuchtli** [comment]
@whitecolor Hopefully I can help you.

I would recommend you look at the the far more popular [airbnb/javascript](https://github.com/airbnb/javascript) style guide which has an order of magnitude more likes than feross/standard.  

As for feross/standard  
 
 1. the stance of semicolons is at odds with 80% of the javascript community.(https://ponyfoo.com/articles/javascript-developer-survey-results#what-javascript-stylistic-choices-do-you-prefer)
 2. The fact feross also named the project *standard* has caused a lot of controversy as it could fool beginner javascript developers into thinking it's the official javascript standard.

As for integrating *feross/standard* for the "sake of simplicity", I doubt adding an extra build/contribution step for a library that's rapidly evolving will not pay off in the short term.

**Comment by whitecolor** [comment]
I understand that it is not "the standard", but it petty good, I don't like semicolons. And cycle codebase style don't use them. Just asked for opinion) I also not completly agree with "standard" in some things like "space before function parentheses" i.e.

**Comment by fiatjaf** [comment]
I use that "standard" whenever I can, but just because it matches almost 100% with the code style I always used. I however wished they had another name, and that it wasn't made by so conceited people.

**Comment by whitecolor** [comment]
I would rather use style with conceited name "standard" than "airbnb". Everything in the world standardizing and unifying, everything follows in one direction)

**Comment by axefrog** [comment]
For what it's worth, semicolons are an error-correction feature. ASI was invented in order to cater for inexperienced/sloppy developers trying to write scripts in the early days of the web. It was never intended as a stylistic choice. If you don't use semicolons, your code has errors. It's just that the JS engine is nice enough to fix them for you.

**Comment by whitecolor** [comment]
And to prevent errors;;;
even more;;;
one just need to;;; 
place several semicolons;;;
at the end;;;
of each line;;;
https://www.youtube.com/watch?v=gsfbh17Ax9I

**Comment by ichpuchtli** [comment]
Quality comment @whitecolor 
I find javascript code with semicolons is much easier to reason about and understand when you glance at it. Semicolons serve to delimit expressions but they also communicate your intentions to people reading your code.

**Comment by whitecolor** [comment]
@ichpuchtli I belive it more a habbit (that gracefully transforms into religeous view). They all came from c/c++, but most web languages prefere to omit them (like pyton, ruby) and othere script that are designed to replace JS with more friendly alternative. Actually I have nothing against them. I just don't like ubiquitous exessive things that we can do fine without, and for me code without semicolons looks cleaner and more pure (hi to "pure script").

**Comment by axefrog** [comment]
@whitecolor heresy!! burn the witch!!

**Comment by whitecolor** [comment]
@axefrog don't worry I can feel your pain)

**Comment by erykpiast** [comment]
Semicolons are tough. You don't like  brackets - you choose python or coffee. You like them - Clojure or any other lisp. Semicolons are not so simple!
