### ISSUE TITLE
Model Driver

### ISSUE THREAD

**Issue by bjfish** [cyclejs/cycle-core#206]
I was working through the http user example and wanted to decouple the http request from the view by including a model which the http request would update and the view would subscribe to model changes.

So, I created a simple driver example using observe js library to observe changes in an object: [Polymer/observe-js](https://github.com/Polymer/observe-js)

The jsbin link for the following example: [JSBin example](http://jsbin.com/jiwoqu/edit?html,js,console,output)

The basic API shown below is `MODEL.select('path.to.subscribe.to')` and the MODEL sink accepts a stream of values at a path to update in the form:
```javascript
     {
              path: 'path.to.update',
              value: 'new.value'
      }
```

I have the following questions:

- Is this a useful pattern? 
- Is there another existing way to achieve this?
- Any suggestions on how to improve this example?

```javascript
const {div, button, h1, h4, a, makeDOMDriver} = CycleDOM;
const {makeHTTPDriver} = CycleHTTPDriver;

function main(sources) {

  const USERS_URL = 'http://jsonplaceholder.typicode.com/users/';
  const getRandomUser$ = sources.DOM
    .select('.get-random').events('click')
    .map(() => {
      const randomNum = Math.round(Math.random()*9)+1;
      return {
        url: USERS_URL + String(randomNum),
        method: 'GET'
      };
    });

  // user remote stream updates the model
  const userRemote$ = sources.HTTP
    .filter(res$ => res$.request.url.indexOf(USERS_URL) === 0)
    .mergeAll()
      .map(res => {
      return {
              path: 'user',
              value: res.body 
      };
    });
  
  // user model stream updates the view
  const userModel$ = sources.MODEL.select('user').startWith(null);
  const vtree$ = userModel$.map(user =>
    div('.users', [
      button('.get-random', 'Get random user'),
      user === null ? null : div('.user-details', [
        h1('.user-name', user.newValue.name),
        h4('.user-email', user.newValue.email),
        a('.user-website', {href: user.newValue.website}, user.newValue.website)
      ])       
    ])
  );

  return {
    DOM: vtree$,
    HTTP: getRandomUser$,
    MODEL: userRemote$
  };
}

function makeMODELDriver(obj){
  return function MODELDriver(obj$){
    function setValue(path, value){
        var obs = new PathObserver(obj, path);
        obs.setValue(value);
    }

    obj$.subscribe( obj => {
      setValue(obj.path, obj.value);
    });
   
    const MODELSource = {
        select: function (path) {
                 
          var source = Rx.Observable.create(function (observer) {
      
                var obs = new PathObserver(obj, path);
                obs.open(function(newValue, oldValue) {
                      observer.onNext({oldValue: oldValue, newValue: newValue });
                      });

                      return function () {
                         // dispose not needed?
                      };
                });
          
              return source;
        }
     };
     return MODELSource;
}; 
}


Cycle.run(main, {
  DOM: makeDOMDriver('#app'),
  HTTP: makeHTTPDriver(),
  MODEL: makeMODELDriver({})
});
```

**Comment by erykpiast** [comment]
I don't think you need model as an object here. That "set property - observe changes on property" layer is transparent. Instead of `MODEL.select('user)` you can have `MODEL.user$`, where `MODEL` is simply hashmap of Observables. You even don't need a driver for that, just create a function with model stream as an input and view as an output, and second one returning model, depending on HTTP driver responses. Your application structure wouldn't be much different, but you could get rid of additional abstraction.

**Comment by staltz** [comment]
This is actually similar to the approach I saw for integrating Falcor with Cycle.js. But it works better with Falcor because the abstraction there is that of remote resources, justifying the use of drivers for the effects. But your `MODEL` approach is local, and there aren't any write/read effects. That's not the use case for a driver. 

I'll close this since it isn't "an issue". If you want to share your ideas, visit the community in the gitter chat.

**Comment by bjfish** [comment]
@staltz Would you consider the `MODEL` a driver with read/write effects if it is given to a child component which causes effects in its parent via this driver?  Example below.

I agree this driver is not a driver with effects when used at the application level but I believe it may be a driver when considering a child component having read/write effects with a parent.

@erykpiast Is there a way to observe read/write a deeply nested model with the hashmap of observables approach? I've only seen simple flat examples likes `Observable.of({  label: 'Height', unit: 'cm', min: 140, initial: 170, max: 210 });`

```javascript
const {Observable} = Rx;
const {div, span, input, makeDOMDriver} = CycleDOM;

// Application
function main(sources) {

  const model = makeMODELDriver({});
  
  Cycle.run(makeTickerComponent('ticks'), { MODEL: model });
  
  const vtree$ = model(Rx.Observable.empty())
  .select('ticks')
  .map(  i => div("Seconds elapsed " + i.newValue));

  return {
    DOM: vtree$
  };
}

// Child Component
function makeTickerComponent(pathToUpdate){
  return function Ticker(sources) {
  const value$ = Rx.Observable.timer(0, 1000).map(res => {

      return {
              path: pathToUpdate,
              value: res
      };
    });
  const sinks = {
    MODEL: value$,
  };
  return sinks;
};
}


Cycle.run(main, {
  DOM: makeDOMDriver('#app')
});



function makeMODELDriver(obj){
  return function MODELDriver(obj$){
    function setValue(path, value){
        var obs = new PathObserver(obj, path);
        obs.setValue(value);
    }

    obj$.subscribe( obj => {
      setValue(obj.path, obj.value);
    });
   
    const MODELSource = {
        select: function (path) {
                 
          var source = Rx.Observable.create(function (observer) {
      
                var obs = new PathObserver(obj, path);
                obs.open(function(newValue, oldValue) {
                      observer.onNext({oldValue: oldValue,                                                                  newValue: newValue });
                      });

                      return function () {
                         // dispose not needed?
                      };
                });
          
              return source;
        }
     };
     return MODELSource;
}; 
}

```

**Comment by bjfish** [comment]
Here is one more experiment  trying to create an observable model with a different syntax.

I like that this syntax allows observing at the deepest level like `user.address.street$` but could also support higher up subscriptions like `user.address$`

```javascript
var user = wrapData({ firstName: "Bob", 
                      address: { "street" : "street 1" }  });


user.address.street$.subscribe(
     function (x) {
        console.log('Next: ' + x.toString());
    });


user.address.street$ = 'street 2'; // Not sure if this is a good way to append 
user.address.street$.onNext('street 3'); 


function wrapData( data ){
      var result = {};
       result.source = data;
      for(var propt in data){
        
         var streamName = propt + "$";
        
        if(data[propt] instanceof Object){
          result[propt] = wrapData(data[propt] );
        } else {
          var subject = new Rx.BehaviorSubject(data[propt]);
          result["_" + streamName] = subject;
          result[propt] = data[propt];
   
        }
          Object.defineProperty(result, streamName, 
             { set: function (x) { result["_" + streamName].onNext(x); },
              get: function() { return result["_" + streamName]; } });

      }
      return result;
}

```

**Comment by HighOnDrive** [comment]
I think your model-driver idea is okay, so don't get me wrong. I'm just tired of hearing about this parent child nested hell and the passing of data and effects in between them and how it's tripping everyone up time and time again. Without proper architecture in the first place Cycle is just begging for all kinds of possible solutions for what should be well laid out in the first place.

Heck, why not just adopt my quick fix it all for once and for all solution, LOL. Just expose the damn KV object of drivers that run creates and allow it to be globally used. That way there is no need to get everyone's shit in a knot about how to mange sources in nested components. That or come up with a well laid plan because obviously there is not one that is good enough yet!
