### ISSUE TITLE
Advice for single source of truth with callbacks

### ISSUE THREAD

**Issue by rbalicki2** [cyclejs/cycle-core#210]
I'd just like to say that I'm very new to this library, and I really really like it so far! I'm excited to build larger apps with it. My apologies if I'm missing the relevant example that could clarify this question.

I am working on a demo todo-list. I'd like to have a single wrapper `ArrayWrapper` that keeps track of the array and the current filter settings, and emits a filtered array. That's pretty easy to set up:

    let filterToggle = FilterToggle({
      DOM,
      initial$: Rx.Observable.of(INITIAL_FILTER)
    });

    let myTodoList = ArrayWrapper(
      Rx.Observable.of(INITIAL_TODOS),
      filterToggle.filter$
    );

    let todoList = TodoList({
      DOM,
      todos$: myTodoList.array$
    });

`ArrayWrapper` currently returns:

    return {
      array$: filteredArray$,
      // I want to return some callbacks here, like function toggle(todoItemId), etc.
    };

I have a few callbacks I'd like to return as sinks from `ArrayWrapper` (this seems like the most obvious way to do it).

Normally, if `ArrayWrapper` was a super-component, it would call `DOM.get('asdf').event('click')` and use some combination of `Rx.Observable.combineLatest` or `scan` to continue emitting the correct array. However, `ArrayWrapper` doesn't know about the DOM, nor should it.

Is there a best practice for exposing a callback, which can then passed to the `TodoList` and executed in a click handler? This strikes me as non-idiomatic, but I'm out of other ideas.

Thank you!

**Addendum**: Since `ArrayWrapper.$array` is an immutable stream, it needs to be passed the streams on which it is dependent (i.e. the TodoList's toggle todo click stream) at creation time. So a solution could be to expose the intent function from the TodoList, pass it to the ArrayWrapper, and then finish creating the TodoList. But that seems overly complicated, so maybe there's something I'm missing.

The alternative is having `clickStream.subscribe(toggleTodo)`, which strikes me as imperative code where it doesn't belong.

**Comment by staltz** [comment]
Hi @rbalicki2, sorry for the delay (I didn't get a notification for this)

> Is there a best practice for exposing a callback, which can then passed to the TodoList and executed in a click handler?

Callbacks or click handlers are anti-patterns in Cycle.js

> The alternative is having clickStream.subscribe(toggleTodo), which strikes me as imperative code where it doesn't belong.

Any use of `subscribe` outside drivers is an anti-pattern in Cycle.js

---

Your ArrayWrapper (if it's a dataflow component, if I understood correctly) should only take streams as input and return streams. Returning functions as callbacks is not the approach. Everything that can possibly affect a dataflow component should be given as a stream to the dataflow component's sources. That's the idea, really. If you keep it simple, and avoid habits like callbacks and remote handlers, just think about what goes in and what comes out, it becomes pretty obvious what should be sources and sinks. The rest is easy. If you feel like some part is overly complicated, it may be you chose to build a dataflow component when you could just use a normal function (every dataflow component is a function but not every function is a dataflow component), or it may be something else wrong with the overall architecture.

Next time, make a question on gitter or stackoverflow and it may be answered quicker.
