### ISSUE TITLE
Rollup + Rx + Cycle == property 'prototype' of undefined

### ISSUE THREAD

**Issue by krainboltgreene** [cyclejs/cycle-core#212]
So this is my code:

``` javascript
import Rx from "rx"
import Cycle from "@cycle/core"
import CycleDOM from "@cycle/dom"

const {Observable} = Rx
const {run} = Cycle
const {button, section, makeDOMDriver} = CycleDOM

const main = () => {
  return {
    DOM: Observable.of(section([button(".decrement", "Down")]))
  }
}

const drivers = {
  DOM: makeDOMDriver("main")
}

run(main, drivers)
```

I receive the error in the title as soon as either line 1 or line 2 are run. I'm using latest everything.

**Comment by erykpiast** [comment]
Did you install Rx manually? Notice it's a peer dependency of cycle-core.

2016-02-16 22:11 GMT+01:00 Kurtis Rainbolt-Greene <notifications@github.com>
:

**Comment by dralletje** [comment]
This is not an issue with cyclejs, it is an rollup issue with rxjs.

Rx does mutate the Rx object to contain all the methods, and it does that by importing the modules manipulating it:
```
...
require('./dist/rx.virtualtime');
require('./dist/rx.testing');

module.exports = Rx;
```

Now the case is, `rx.testing` depends on `rx.virtualtime` being executed already. I don't know why (I'll open an issue for rollup/look into it) but Rollup executes the modules in reverse order. That means that the changes made in `rx.virtualtime` are not yet present when running `rx.testing`, yielding this error.

A workaround for now is, when importing `rx`, explicitly importing the `rx.virtualtime` module first:
```
import 'rx/dist/rx.virtualtime'
import Rx from 'rx'
```

Hope this helps you out! :)

**Comment by dralletje** [comment]
@staltz you can close this issue I think, as it is an Rollup problem rather than Cycle-core one :)

**Comment by staltz** [comment]
Yes sir, thanks :)
