### ISSUE TITLE
Weird things happening with DOM and HTTP drivers

### ISSUE THREAD

**Issue by chadrien** [cyclejs/cycle-core#215]
Hi,

First of all, I open this issue in cycle-core as I'm not sur if it's specifically related to the DOM driver, the HTTP driver or something else.

Consider the following piece of code:

```js
import { Observable } from 'rx'
import { run } from '@cycle/core'
import { makeDOMDriver, div } from '@cycle/dom'
import { makeHTTPDriver } from '@cycle/http'

function main(sources) {
  return {
    DOM: sources.HTTP
      .filter(res$ => res$.request.url === 'http://jsonplaceholder.typicode.com/posts/1')
      .mergeAll()
      .map(() => div(['foo'])),
    HTTP: Observable.just({url: 'http://jsonplaceholder.typicode.com/posts/1'})
  }
}

run(main, {
  DOM: makeDOMDriver('#app'),
  HTTP: makeHTTPDriver()
})
```

What (I think) it does: start an HTTP GET query and then display a div once the request is done. Is this correct?

What happens: sometimes (when the stars align, 4 out of 10 tries) when I run this with the inspector open, I can see that 2 requests are actually done.

![cycle](https://cloud.githubusercontent.com/assets/1788218/13254862/a9b77eb6-da43-11e5-8ed9-b710f8bb1734.gif)

So what did it do wrong? :smiley: 

Edit: I've made a [jsbin](https://jsbin.com/suvara/2/edit?js) so you can see the result by yourselves easily: http://output.jsbin.com/suvara

**Comment by TylorS** [comment]
Using your JSBin example, I'm only seeing one HTTP request
![image](https://cloud.githubusercontent.com/assets/6282473/13255872/394482dc-da16-11e5-84ce-294af5a5cc57.png)

**Comment by erykpiast** [comment]
I've got two, but the first one is OPTIONS request (no idea why it's sent
before GET, I guess it's related with XHR library used in cycle-http).

[image: Obraz w treści 1]

2016-02-23 16:15 GMT+01:00 Tylor Steinberger <notifications@github.com>:

**Comment by staltz** [comment]
> I've got two, but the first one is OPTIONS request 

That's because of CORS.

JSBin and HTTP driver are not friends. JSBin itself has some restrictions to which servers you may make requests to, that's why the output needs to be run from `http` not `https`.

Anyway, nothing mysterious is happening here in my opinion. The OPTIONS request is just a CORS preflight request: http://www.html5rocks.com/en/tutorials/cors/

**Comment by erykpiast** [comment]
Oh, it's so obvious, I didn't noticed! But @chadrien, is it what you have seen?

**Comment by chadrien** [comment]
Yep totally didn't noticed one of them was an OPTION request.
