### ISSUE TITLE
dependecy on emiiter and reduce

### ISSUE THREAD

**Issue by staltz** [cyclejs/cycle-core#237]
_From @mamciek on February 2, 2016 13:24_

I cannot load http-driver because it tries to load emitter.js and reduce.js . Shouldn't them be declared as dependencies?

var Emitter = require('emitter');
var reduce = require('reduce');

_Copied from original issue: cyclejs/cycle-http-driver#43_

**Comment by staltz** [comment]
_From @mamciek on February 2, 2016 15:15_

I am also having problem with 
`var Rx = (typeof window !== "undefined" ? window['Rx'] : typeof global !== "undefined" ? global['Rx'] : null);`

Why isn't rx loaded with `require('rx')` ?

**Comment by staltz** [comment]
_From @TylorS on February 2, 2016 21:6_

I don't have any idea where you're getting `emitter.js` or `reduce.js` from, but Rx is a peer dependency. It's expected to be loaded from a separate file like : `https://cdnjs.cloudflare.com/ajax/libs/rxjs/4.0.6/rx.all.js`

**Comment by staltz** [comment]
_From @TrippBlunschi on February 12, 2016 23:19_

I get the same error when trying to load with jspm.

`"jspm": {
    "name": "tricycle",
    "dependencies": {
      "@cycle/core": "npm:@cycle/core@6.0.2",
      "@cycle/dom": "npm:@cycle/dom@9.0.2",
      "@cycle/http": "npm:@cycle/http@8.0.0",
      "rx": "npm:rx@^4.0.7"
    },`

**Comment by staltz** [comment]
_From @TrippBlunschi on February 12, 2016 23:30_

Adding the cdn to rx.all.js solves the problem, but that shouldn't be necessary, correct? In my case, JSPM loads rx as a peer dependency.

**Comment by staltz** [comment]
I don't use JSPM. Can you submit a PR to fix this for your use case?

**Comment by staltz** [comment]
_From @jamesgorrie on February 24, 2016 9:8_

If you require `Rx` into the file it should work, as @TylorS mentioned, `Rx` it's expected to be loaded.

e.g.
__Doesn't work__
```JS
import Cycle from '@cycle/core';
import CycleHTTPDriver from '@cycle/http';
```

__Does work__
```JS
import Rx from 'rx';
import Cycle from '@cycle/core';
import CycleHTTPDriver from '@cycle/http';
```

**Comment by jamesgorrie** [comment]
@staltz - from the last bug I also mentioned that this isn't really a fix.
I will try to work on one when I have time.
