### ISSUE TITLE
AMD

### ISSUE THREAD

**Issue by chiplay** [cyclejs/cycle-core#4]
Hey @staltz! I read your post and I'm really excited to try out this MVI pattern.  The app environment we're in is AMD (require.js) and I can't seem to get Cycle to return properly w/wo shims.  Any thoughts on how to get it to play nice with the require.js ecosystem?  Thanks!

**Comment by staltz** [comment]
Closed because too silent too long indicates no interest, and the PR above might have solved it for those who need it.
