### ISSUE TITLE
Browser support?

### ISSUE THREAD

**Issue by kimmobrunfeldt** [cyclejs/cycle-core#76]
What's the browser support for Cycle.js? Sorry if I missed it from docs.

**Comment by staltz** [comment]
It used to be the same as virtual-dom intersection with RxJS, but now with custom elements I am using some things that I'm not quite sure are supported on older browsers. I should put up a compatibility test, but as stated, right now I'm focusing on getting the core API done ASAP, so performance and compatibility and these sort of issues are secondary.

**Comment by kimmobrunfeldt** [comment]
If you'd want to automate tests for various real browsers. I would probably go with [BrowserStack](http://www.browserstack.com/). I have used [SauceLabs](https://saucelabs.com/) but browserstack has more browsers and seems a bit better when I gave a look at the tooling.

**Comment by staltz** [comment]
This issue was moved to cyclejs/cycle-web#8
