### ISSUE TITLE
interactions.get() should respect scope of child custom element 

### ISSUE THREAD

**Issue by staltz** [cyclejs/cycle-core#84]
Currently, `User.event$('.foo', 'click')` selects all `.foo` under the User's root node, including `.foo` which lives inside a custom element. We don't want the querySelector to look inside child custom elements. We might need to use the Shadow DOM (the polyfill?) for that. Or, as a shotgun solution, just make all Cycle custom elements become full-blown web components. That would be a nice side benefit of fixing this bug.

**Comment by erykpiast** [comment]
That's the thing!

**Comment by ivan-kleshnin** [comment]
@erykpiast how much is the size of those polyfills size in kb? Do you tried them in practice?

**Comment by erykpiast** [comment]
They are (or it is actually - http://webcomponents.org/) quite big - 105 kB minified, 31 kB gzipped. Sounds scary, I know, but always, it depends. Anyone, who wants to use Polymer on production, has to use it.

But, we probably don't need all Web Components parts - only Custom Elements and Shadow DOM. I can't imagine, how we can use Templates with VirtualDOM (but it would be awesome), HTML Imports aren't required at all. So, we need at least ~80 kB (~24 kB gzipped) of polyfills - 9.9 kB (3.7 kB) for Custom Elements and 69 kB (20 kB) for Shadow DOM.

**Comment by staltz** [comment]
I'm trying not to optimize for size first. So much can change in the near future, that it really isn't the biggest concern at the moment. I am a bit disturbed with the size of RxJS, but that doesn't stop me from adding it to Cycle. Shrinking down that size should come after API design.

Then there is also HTTP2 which will improve performance so much that these kB won't become a problem. And also Shadow DOM is supposed to be implemented natively in browsers so we won't be needing that polyfill forever either.

**Comment by erykpiast** [comment]
:+1:

**Comment by ivan-kleshnin** [comment]
If we have custom element `Picture` should't 
```javascript
User.event$("Picture", "click").subscribe(() => console.log("Picture.click!");
```
also works?

**Comment by staltz** [comment]
event$() selector is much weaker than document.querySelectorAll(). I recommend using only classnames as selectors, but it's a good point that probably anything else should be supported (ids and tagnames). This will probably be fixed. :+1:

**Comment by staltz** [comment]
This issue might not be relevant anymore if we build https://github.com/staltz/cycle/issues/115

**Comment by arlair** [comment]
It looks like you don't need Shadow DOM, but if you go down the road there is a cut down version called Shady DOM. Shady DOM is used by Polymer.

https://www.polymer-project.org/1.0/articles/shadydom.html

**Comment by staltz** [comment]
This issue was moved to cyclejs/cycle-web#13
