### ISSUE TITLE
Any thoughts on testing?

### ISSUE THREAD

**Issue by erykpiast** [cyclejs/cycle-core#86]
I'm a bit concerned about testability of Cycle. It seems mocking DataFlowNodes isn't so hard, but this still requires some boilerplate code. Don't you think that make testing nice and easy should be one of the most important thing in any framework? I can't find any tests in example apps linked on Cycle GitHub page, so I have no idea, if it was considered at all. I don't propose anything for now, just draw an attention. I'm going to create unit tests for couple of Web Components created with Cycle (https://github.com/erykpiast/autocompleted-select is one of them), and after that I'll be able to elaborate the topic more.

**Comment by staltz** [comment]
Yes there should be example tests (and actually, there should be more examples). This is important, but it's not top priority (which is API design).

Mocking DataFlowNodes is essentially about mocking the observables it exports, and the tool for that is already in RxJS: TestScheduler, Rx.ReactiveTest, etc. See an example here: https://github.com/Reactive-Extensions/RxJS/blob/master/tests/observable/debounce.js
