### ISSUE TITLE
Create iOS Driver based on React Native

### ISSUE THREAD

**Issue by staltz** [cyclejs/cycle-core#91]
Let's experiment with making an iOSUser/iOSRenderer (analogous to DOMUser) which internally uses React Native to make iOS native components.

**Comment by erykpiast** [comment]
it's awesome idea, to try at least! (and you are really fast : )

**Comment by fattenap** [comment]
:+1:  That does sound awesome!!

**Comment by staltz** [comment]
Got something working! I needed to change `rx` to `rx-lite` and hack one line of code deep inside React Native, but it is roughly working. Open sourcing the changes soonish.

**Comment by erykpiast** [comment]
:congratulations:

**Comment by staltz** [comment]
Now just need to wait for the JS universe to converge on a fix: https://github.com/facebook/react-native/issues/447

**Comment by staltz** [comment]
Should be good with React Native 0.3.4.

**Comment by staltz** [comment]
Here is a gist of what I had working. https://gist.github.com/staltz/0d92dc4409a471f83c48
Cycle.js at version 0.18.2 and React Native at version 0.3.4.

I'll make an experimental repo for this library once I'm done with the new streams API. Also notice there is only Model => View => Renderer in this experiment. No Intent to handle events, yet.

**Comment by staltz** [comment]
This issue is resolved by the existence of https://github.com/cyclejs/cycle-react-native, which is currently experimental, but additional development of such driver should be discussed in that repository, not this one.
